version: '3'

services:
    web:
        #image:  beego-hello:latest
        build: ./beego-hello/
        restart: always
        #ports:
        #    - "80"
    # listen on local docker sock to register the container with public ports to the consul service
    registrator:
        image: gliderlabs/registrator:master
        hostname: registrator
        restart: always
        links:
            - consul-server:consul
        volumes:
            - "/var/run/docker.sock:/tmp/docker.sock"
        command: -internal consul://consul-server:8500
        #depends_on:
        #    - consul-server
        #    - nginx-template
    consul-server:
        image: progrium/consul:latest
        #environment:
        #    SERVICE_TAGS: consul servers
        hostname: consul
        restart: always
        ports:
            #- "8300"
            #- "8400"
            - "8500:8500"
            #- "53"
        command: -server -ui-dir /ui -bootstrap-expect 1
    #load balancer will automatically update the config using consul-template
    nginx-template:
        #image: nginx-consul-template-image:latest
        build: nginx-consul-template
        hostname: nginx-template
        restart: always
        volumes:
            - "./nginx-consul-template/nginx/www:/usr/share/nginx/html"
            - "./nginx-consul-template/nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
            - "./nginx-consul-template/nginx/conf/conf.d:/etc/nginx/conf.d"
            - "./nginx-consul-template/nginx/log:/var/log/nginx"
        links:
            - consul-server:consul
        ports:
            - "8100:80"
        #http（web）
        #depends_on:
        #    - consul-server



