version: "3.5"

services:
    elasticsearch:
        container_name: elasticsearch
        image: elasticsearch:7.6.0             #镱像(image)
        restart: always                        #重启方式
        environment:
            discovery.type: single-node          #环境变量：运行模式 单例
        ports:
            - "9200:9200"                        #端口映射
            - "9300:9300"
    kibana:
        container_name: kibana
        image: kibana:7.6.0                     #镱像(image)
        restart: always                         #重启方式
        environment:
            I18N_LOCALE: "zh-CN"                  #指定中文
        ports:
            - "5601:5601"                          #端口映射
    logstash:
        container_name: logstash
        image: logstash:7.6.0
        restart: always
        volumes:                                #文件夹映射，本地:容器
            - "/data/docker/logs:/usr/share/logstash/logs"
        ports:
            - "5044:5044"
            - "9600:9600"